// Define Navigation Routes
const NavigationRoutes = {
  Login: 'Login',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  Dashboard: 'Dashboard',
  Profile: 'Profile',
  ProfileSetting: 'ProfileSetting',
  JoinEvent: 'JoinEvent',
  AdminInfo: 'AdminInfo',
  MpinCode: 'MpinCode',
  AddEvent: 'AddEvent',
  UpdateEvent: 'UpdateEvent',
  AddImage: 'AddImage',
  EventScreen: 'EventScreen',
  AddUser: 'AddUser',
  OtpVerification: 'OtpVerification',
  EventCalendar: 'EventCalendar',
  UpcomingEvents: 'UpComingEvents',
  SocialMedia: 'SocialMedia',
  WebsiteLink: 'Website Link',
  EventProfile: 'EventProfile',
  EventPoll: 'EventPoll',
  EventChoiceList: 'EventChoiceList',
  PollResults: 'PollResults',
  ChoiceResults: 'ChoiceResults',
  ResetPassword: 'ResetPassword',
  CreateNote: 'CreateNote',
  AddDocument: 'AddDocument',
  EventDetail: 'EventDetail',
  AddWebsite: 'AddWebsite',
  RsvpForm: 'RsvpForm',
  AddChecklist: 'AddCheckList',
  AddVoteOrPoll: 'AddVoteOrPoll',
  AddChoiceList: 'AddChoiceList',
  EventCheckList: 'EventCheckList',
  AddSocialMedia: 'AddSocialMedia',
  RsvpComments: 'RsvpComments',
  AddRSVP: 'AddRSVP',
  ConfirmPin: 'ConfirmPin',
  EventNote: 'EventNote',
  EventLocation: 'EventLocation',
  AddLocation: 'AddLocation',
  GuestEventProfile: 'GuestEventProfile',
  GuestList: 'GuestList',
  TermsCondition: 'TermsCondition',
  PrivacyPolicy: 'PrivacyPolicy',
  AboutUs: 'About Us',
  ReportToAdmin: 'Report To Admin',
  Help: 'Help',
  SupportFeedBack: 'Support and Feedback',
  EventDocument: 'Event Document',
  DocumentViewer: 'Document Viewer',
  ResetMPin: 'Reset MPin',
  UserInfo: 'User Info',
  EventScheduleList: 'Event Schedule List',
  UpdateEventScheduleList: 'Update Event Schedule List',
  AddEventSchedule: 'Add Event Schedule',
  CreateRsvp: 'Create RSVP',
};

export default NavigationRoutes;
