export const Strings = {
  OtpSent: 'OTP has been sent on your Email address',
  Ok: 'Ok',
  JobOffer: 'JobOffer',
  Login: 'Login',
  LoginTitle: 'Log In',
  EnterEventCode: 'Enter Event Code',
  JoinEvent: 'Join Event',
  GoToDashBoard: 'Go To Dashboard',
  ForgotPassword: 'Forgot Password ?',
  ForgotMpin: 'Forgot M-pin ?',
  ForgotPasswordTitle: 'Forgot Password',
  ResetPassword: 'Reset Password',
  DontHaveAccount: 'Don’t have an account? ',
  BackToLogin: 'Back to login? ',
  termsConditionText: 'Terms & Condition ',
  PrivacyPolicyText: ' Privacy Policy',
  AboutUs: 'About Us',
  ScheduleEvent: 'Schedule Event',
  UpdateScheduleEventList: 'Update Event Schedule',
  AddScheduleEventList: 'Add Event Schedule',
  SignUp: 'Signup',
  SignUpTitle: 'Sign Up',
  VerifyEmail:
    'Verification link has been send to your registered email, Please check it...',
  SignIn: 'SignIn',
  haveAccount: 'Have an account? ',
  sendOtp: 'Send OTP',
  sendMessage: 'Send Message',
  password: 'password',
  joinEvent: 'Join Event',
  EnterCode: 'Enter the code you received',
  Bio: 'Bio',
  Name: 'Name',
  Email: 'Email',
  SocialMedia: 'Social Media',
  CreateEvent: 'Create Event ',
  TeamPage: 'Team Page',
  UpdateEvent: 'Update Event',
  Next: 'Next',
  Update: 'Update',
  CreateNext: 'Create / Next',
  EnterNoteTitle: 'Enter Note Title',
  AddTitle: 'Add Title',
  addTeamName: 'Add Team Name',
  AddNoteText: 'Add Note Text',
  AddDescription: 'Add Description',
  EnterTitle: 'Enter Title',
  enterTeamName: 'Enter Team Name',
  EventDescription: 'Enter Description',
  EventStartDate: 'Start Date',
  EventStartTime: 'Start Time',
  EventEndDate: 'End Date',
  EventEndTime: 'End Time',
  MonthDate: 'Event Month Date',
  EventDate: 'Event Date',
  AddContacts: 'Add Contacts',
  MeetingType: 'Meeting Type',
  PickColorMeeting: 'Pick Color For Meeting',
  AddLocation: 'Add Location',
  AddLocationForEvent: 'Add Location for your Event or Sports Team',
  AddHomeClubLocation: 'Add home club location',
  AddEventLocation: 'Add Event Location',
  LocationAddress: ' 346 W Cedar Ave, Gladwin, Michigan, 48624',
  Contacts: 'Contacts',
  MultipleEvent: 'Multiple Event',
  adminInfo: 'Admin Info',
  InfoTabs: 'InfoTabs',
  createEvent: 'Create Event',
  Mpin: 'M-Pin',
  EnterMpinCode: 'Enter your M-pin code',
  AddImage: 'Add Image',
  Save: 'Save',
  UploadYourFilesHere: 'Upload Your files here',
  Browse: 'Browse',
  Upload: 'Upload',
  Files: 'Files',
  Events: 'Events',
  AddUser: 'Add User',
  AddGuest: 'Add Guest',
  Add: 'Add',
  And: 'and',
  No: 'No',
  Yes: 'Yes',
  Continue: 'Continue',
  OtpVerification: 'OTP Verification',
  EnterOtp: 'Enter Code',
  EventCalendar: 'Event calendar',
  UpcomingEvents: 'Upcoming Events',
  Facebook: 'Facebook',
  Instagram: 'Instagram',
  Twitter: 'Twitter',
  LinkedIn: 'LinkedIn',
  JuniorLeague: 'Junior League',
  participantNumber: '20 Participant',
  EventPoll: 'Event Poll',
  EventCheckList: 'Event CheckList',
  EventChoiceList: 'Event ChoiceList ',
  PollResults: 'Poll Results',
  Vote: 'VOTE',
  Votes: 'Votes',
  CreateNote: 'Create Note',
  title: 'Title',
  Description: 'Description',
  GenerateMpin: 'Generate Mpin',
  AddDocument: 'Add Document',
  AddWebsite: 'Add Website Link',
  docPdf: 'doc.pdf',
  WebsiteLink: 'Website Link',
  Poll: 'Poll',
  RSVP: 'RSVP',
  Document: 'Document',
  Location: 'Location',
  Calendar: 'Calendar',
  Note: 'Note',
  Photo: 'Photo',
  startDate: 'Start Date',
  endDate: 'End Date',
  startTime: 'Start Time',
  endTime: 'End Time',
  Website: 'Website',
  EventType: 'Event Type',
  EventInfo: 'Event Info',
  TeamInfo: 'Team Info',
  Team: 'Team',
  Guests: 'Guests',
  ViewAll: 'View All',
  MessageHere: 'Message here...',
  RSVPForm: 'RSVP Form',
  Attending: 'ATTENDING',
  NotAttending: 'NOT ATTENDING',
  Time: 'Time',
  TimeText: '1st July, 2023',
  CodyBankArena: 'Cody bank arena',
  JuniorWorldCup: 'Junior World Cup',
  rsvpTitle: 'RSVP Title : ',
  rsvpDescription: 'RSVP Description : ',
  AddCheckList: 'Add Check List',
  AddListHere: 'Add list here',
  CheckTitle: 'Check Title',
  Delete: 'Delete',
  AddMore: 'Add More +',
  AddMoreOption: 'Add More Option',
  AddMoreList: 'Add More List',
  AddVoteOrPoll: 'Add Vote or Poll',
  VoteTitle: 'Vote Title',
  CheckListTitle: 'Checklist Title',
  VoteOption: 'Vote Option',
  AddChecklist: 'Add check list',
  AddChoiceList: 'Add Choice List',
  ChoiceTitle: 'Choice Title',
  AddSocialMedia: 'Add Social Media',
  AddSocialMediaOrWebsite: 'Add social media or website',
  SocialMediaLink: 'Social Media Link',
  Edit: 'Edit',
  Settings: 'Settings',
  AccountSetting: 'Account Setting',
  ThemeMode: 'Theme Mode',
  Notification: 'Notification',
  StorageAndData: 'Storage & Data',
  Help: 'Help',
  EnterEventDateandTime: 'Enter Event Date and Time',
  InviteFriends: 'Invite Friends',
  Logout: 'Log Out',
  ReportToAdmin: 'Report To Admin',
  RsvpResponses: 'RSVP Responses',
  Attend: 'Attend',
  unAttend: 'Not Attend',
  AddRSVP: 'Add RSVP',
  ImportCalendar: 'Import Calender',
  Password: 'Password',
  TermsAndCondition: 'Terms & Condition',
  PrivacyPolicy: 'Privacy Policy',
  SupportAndFeedback: 'Support & Feedback',
  ConfirmYourPin: 'Confirm Your Pin',
  ConfirmYourNewMPin: 'Confirm Your New M Pin',
  ConfirmPinBottomHeading: 'This keeps your account secure.',
  EventNote: 'Event Note',
  SelectImage: 'Select Image',
  Select: 'Select',
  EventLocation: 'Event Location',
  UseMyCurrentLocation: 'Use My current Location',
  MuteParticipant: 'Mute Participant',
  MuteChat: 'Mute Chat',
  MuteNotification: 'Mute Notification',
  Guest: 'Guest',
  MultiEvent: 'Event Schedule List',
  Or: 'Or',
  LoginWithMPin: 'Login with M-pin',
  StoragePermissionRequired: 'Storage Permission Required',
  StoragePermissionNotGranted: 'Storage Permission Not Granted',
  AppNeedsAccessToYourStorageToDownloadPhotos:
    'App needs access to your storage to download Photos',
  Image: 'Image',
  ImageDownloadedSuccessfully: 'Image Downloaded Successfully',
  update: 'Update',
  SelectLocation: 'Select Location',
  SelectEventType: 'Select Event Type',
  enterYourPin: 'Enter Your Pin',
  enterYourNewMPin: 'Enter Your New M-Pin',
  customRight: 'custom_right',
  Admin: 'Admin',
  User: 'User',
  TermsPrivacyTitle: 'Terms & Privacy',
  EventDocumentTitle: 'Event Document',
  rsvpExpired: 'RSVP Expired',
  seeResult: 'See Result',
  rsvpDate: 'Date : ',
  rsvpTime: 'Time: ',
  RSVPDate: 'Rsvp Date : ',
  RSVPTime: 'Rsvp Time : ',
  accept: 'Accept',
  decline: 'Decline',
  teamEvent: 'Team or open event, no specific date required.',
  choiceListOptions: 'ChoiceList Options',
  ChoiceResult: 'Choice Result',
  PrivateMode: 'Private Mode',
  NoDataAvailable: 'No data available',
  ChooseYourFunction: ' Choose your function',
  TeamManager: 'Team Manager',
  TeamManagerDesc:
    ' Perfect for Sports teams with multiple dates, fixtures locations & more',
  SingleEvent: 'Single Event',
  SingleEventDesc:
    ' Perfect for one off events like Weddings, Parties, Holidays, BBQ’s Get togethers & more',
  SoQuietHereRightNow: 'So quiet here right now',
  noEvents: ' Tap the + button below to create or join an event or a team page',
  // Placeholder Strings
  firstNamePlaceholder: 'First Name',
  lastNamePlaceholder: 'Last Name',
  PasswordPlaceholder: 'Password',
  emailPlaceholder: 'Email',
  phoneNumber: '+1 (226) 261-0268',
  NOImgFound: 'No Image Found',
  PhoneNumberPlaceholder: 'Phone Number',
  confirmPasswordPlaceholder: 'Confirm Password',
  name: 'Name',
  namePlaceholder: 'Kimberly',
  socialMedia: 'Social Media',
  socialMediaPlaceholder: 'https://www.facebook.com/',
  camera: 'Camera',
  gallery: 'Gallery',
  cancel: 'Cancel',
  Comment: 'Comment...',
  joinNow: 'Join Now',
  PhoneNumber: 'Phone Number',
  NamePlaceholder: 'Enter Name',
  EmailPlaceholder: 'Enter Email',
  SocialMediaPlaceholder: 'website link',
  BioPlaceholder: 'Enter Bio',
  SearchEvent: 'Search Event',
  SearchLocation: 'Search Location',
  SearchEventType: 'Search Event Type',
  EmailAddressPlaceholder: 'Email Address',
  AddGuestPlaceholder: 'Add Guest',
  addCommentPlaceholder: 'Add Comment',
  Daily: 'Daily',
  Weekly: 'Weekly',
  Monthly: 'Monthly',
  AddWebsiteLinkPlaceholder: 'Please add website link',
  AddWebsiteLinkTitlePlaceholder: 'Please add Website Title',
  EnterTitlePlaceholder: 'Enter Title',
  TitleHere: 'Title here',
  LocationNamePlaceholder: 'Location Name',
  ContactNumberPlaceholder: 'Enter Contact Number',
  AddressPlaceholder: 'Address',
  CountryNamePlaceholder: 'Country Name',
  CityNamePlaceholder: 'City Name',
  StateNamePlaceholder: 'State Name',
  VoteOptionHere: 'Vote option here...',
  checkLists: 'Checklists',
  CheckList: 'Check List',
  ChoiceList: 'Choice List',
  ChoiceOptionHere: 'Choice option here...',
  LinkHere: 'Link here...',
  FacebookLinkHere: 'Facebook Link here...',
  InstagramLinkHere: 'Instagram Link here...',
  TwitterLinkHere: 'Twitter Link here...',
  LinkedInLinkHere: 'LinkedIn Link here...',
  DeleteDocument: 'Delete Document',
  ChatIsEmpty: 'Chat is Empty',
  deleteOptions: 'Delete Options',
  choiceListTitle: 'ChoiceList Title',
  phoneNoValidation: 'Phone number must have 10 digits',
  PhoneError: 'Enter valid phone number',
  // Error Strings
  EmptyUserName: 'User name can not be empty',
  EmptyGuestName: 'Guest name can not be empty',
  EmptyEmail: 'Email can not be empty',
  EmptyMessage: 'Message can not be empty',
  EmptySubject: 'Subject can not be empty',
  EmptyPassword: 'Password can not be empty',
  EmptyFirstName: 'First name can not be empty',
  EmptyLastName: 'Last name can not be empty',
  EmptyContactNumber: 'Contact number can not be empty',
  EmptyContactNumberValidations: 'Phone number should be 10 digits',
  EmptyLocationName: 'Location name can not be empty',
  EmptyAddress: 'Address can not be empty',
  EmptyCity: 'City can not be empty',
  EmptyCountry: 'Country can not be empty',
  EmptyState: 'State can not be empty',
  EmptyInvitationCode: 'Invitation code can not be empty',
  InvitationCodeValidation: 'Please enter 6 digit invitation code',
  PhoneNumberError: 'Phone number must contain only digits',
  EmailError: 'Please enter a valid email address',
  EmptySocialLinks: 'Please enter at least one social media link',
  invalidSocialMediaLink: 'Enter Valid social media Link.....',
  invalidWebsiteLink: 'Enter Valid website Link.....',
  invalidFacebookLink: 'Enter Valid facebook Link.....',
  invalidInstaLink: 'Enter Valid Instagram Link.....',
  invalidTwitterLink: 'Enter Valid Twitter Link.....',
  invalidLinkedInLink: 'Enter Valid LinkedIn Link.....',
  PasswordError: 'Password must be at least 6 characters long',
  ConfirmPasswordError: 'Passwords do not match',
  WhiteSpaceNotAllowed: 'White space is not allowed here.',
  PasswordShouldBe:
    'The minimum password length should be 8 characters and must contain at least 1 lowercase and uppercase letter, number and special character.',
  InvalidPassword: 'Please enter valid password.',
  PasswordNotMatch: 'Please make sure your password match',
  EmptyConfirmPassword: 'Confirm Password can not be empty',
  documentPickerError: 'Please select up to 4 files only',
  EmptyOtp: 'Please enter Otp.',
  EmptyVoteTitle: 'Vote title can not be empty',
  EmptyChoiceListTitleTitle: 'Choicelist title can not be empty',
  EmptyVoteOptions: 'Vote options can not be empty',
  VoteOptionError: 'Vote option should be more than one option',
  ChecklistOptionError: 'please enter at least one list option',
  ChoicelistOptionError: 'Choice list option should be more than one option',
  InvalidOtp: 'Please enter valid otp.',
  EmptyTermsAndCondition: 'Please agree Terms & condition..',
  MPINMatchError:
    'MPIN and Confirm MPIN do not match. Please make sure you enter the same MPIN in both fields.',
  InviteUserError: 'Something Went Wrong',
  EventParticipantError:
    'Event Participants have not been added successfully. Something went wrong',
  LogoutConfirmation: 'Are You sure you want to logout?',
  DeleteNoteConfirmation: 'Are You sure you want to delete note?',
  DeleteRSVPConfirmation: 'Are You sure you want to delete RSVP?',
  DeleteWebLinkConfirmation: 'Are You sure you want to delete WebLink?',
  DeletePollOptionConfirmationPoll: 'Are you sure you want to delete?',
  DeleteMessageConfirmation: 'Are you sure you want to delete message?',
  DeleteChatImageConfirmation: 'Are you sure you want to delete image?',
  DeleteScheduleConfirmation: 'Are you sure you want to delete schedule?',
  DeleteEventConfirmation: 'Are you sure you want to delete this event?',
  DeleteCheckListOptionConfirmationPoll: 'Are you sure you want to delete?',
  EventTypeError: 'Please select any event type..',
  BlankEventError: 'EventName can not be blank....',
  InvalidEndDate: 'Enter valid end Date...',
  endTimeValidation: 'End time can not be same as start time',
  LocationSelectionError: 'Please select any Location...',
  NoUserFoundError: 'No user found',
  NoEventGuestFoundError: 'No Event Guest Found',
  joinEventCode: 'Please Enter at least 6 characters.',
  NoInfoChirpsAdded: 'No info added by host just yet',
  BlankNoteTitleError: 'Note title can not be blank...',
  BlankNoteDescriptionError: 'Note Description can not be blank...',
  DeleteDocumentConfirmation: 'Are You sure you want to Delete This Document ?',
  EmptyWebLinkTitle: 'Website title can not be empty',
  EmptyChecklistTitle: 'Checklist title can not be empty',
  EmptyChecklistOptions: 'Checklist options can not be empty',
  EmptyWebsiteLink: 'Website link can not be empty',
  ValidWebsiteLink: 'Please add valid Website Link.....',
  GuestUserValidation: 'Guest can not be blank.',
  ValidMpin: 'Please enter the proper M-Pin.',
  generateMpinRequest: 'Would you like to generate Mpin?',
  EmptyPollOption: 'please select at least one option',
  NoUserFound: 'No User Found!',
  EmptyRSVPTitle: 'RSVP title can not be empty.',
  EmptyRSVPDesc: 'RSVP description can not be empty.',
  NoMultiEventFound: 'Event Schedule List Not Found',
  NoUpcomingEventFound: 'Upcoming Event List Not Found',
  SearchUser: 'Search Users',
  DeleteEvent: 'Delete Event',
};
