const mockImages = {
  ProfileSelection1: require('./profileSelection1.png'),
  ProfileSelection2: require('./profileSelection2.png'),
  Hockey: require('./hockey.png'),
  FIH_Pro_League: require('./FIH_Pro_League.png'),
  Junior_World_Cup: require('./Junior_World_Cup.png'),
  FIH_Congress: require('./FIH_Congress.png'),
  Indoor_World_Cup: require('./Indoor_World_Cup.png'),
  Youth_Hokey_Games: require('./Youth_Hokey_Games.png'),
  Hokey_Premium_League: require('./Hokey_Premium_League.png'),
  addUser1: require('./addUser1.png'),
  addUser2: require('./addUser2.png'),
  addUser3: require('./addUser3.png'),
  addUser4: require('./addUser4.png'),
  addUser5: require('./addUser5.png'),
  addUser6: require('./addUser6.png'),
  addUser7: require('./addUser7.png'),
  addUser8: require('./addUser8.png'),
  addUser9: require('./addUser9.png'),
  addUser10: require('./addUser10.png'),
  addUser11: require('./addUser11.png'),
  addUser12: require('./addUser12.png'),
  addUser13: require('./addUser13.png'),
  addUser14: require('./addUser14.png'),
  selectIcon: require('./selectIcon.png'),
};
export default mockImages;
